"""DTOs for basic answer use case."""

from typing import Literal
from uuid import uuid4

from pydantic import BaseModel, Field


class ConfigDTO(BaseModel):
    """Configuration for the answer request."""

    conversation_id: str = Field(default_factory=lambda: str(uuid4()))


class AnswerRequestDTO(BaseModel):
    """Request DTO for basic question-answering."""

    config: ConfigDTO = Field(default=..., description="Configuration for the answer request.")
    message: str = Field(default=..., description="The user's message to the assistant.")


class AssistantMessageDTO(BaseModel):
    """DTO representing a message from the assistant."""

    role: Literal["assistant"] = "assistant"
    content: str


class AnswerResultDTO(BaseModel):
    """Result DTO containing the assistant's response."""

    conversation_id: str
    message: AssistantMessageDTO


class AnswerStreamEventDTO(BaseModel):
    """
    Stream event DTO for real-time streaming responses.

    Used with Server-Sent Events (SSE) or NDJSON to stream partial
    responses as they're generated by the LLM.

    This enables a better UX where users see the response appear word-by-word
    rather than waiting for the complete response.

    Attributes:
        kind: Event type - "delta" for partial content chunks, "done" for completion.
        delta: Partial content fragment (None for "done" events).

    Example Stream:
        ```python
        # First events (partial responses)
        {"kind": "delta", "delta": "The"}
        {"kind": "delta", "delta": " capital"}
        {"kind": "delta", "delta": " of France"}
        {"kind": "delta", "delta": " is Paris"}
        {"kind": "delta", "delta": "."}
        # Final event (signals completion)
        {"kind": "done", "delta": null}
        ```

    Design Note: We keep this simple with just "delta" and "done".
    More advanced implementations might add:
    - "start" event with metadata
    - "error" event for failures
    - "metadata" event for token counts, timing, etc.
    """

    kind: Literal["delta", "done"] = "delta"
    delta: str | None = None
